/**
 * Shared types for the MF Voice Advisor project.
 * Matches Master Doc Section 5 (Data Models) and Section 7 (ConversationState).
 */

// ---------------------------------------------------------------------------
// Conversation State (Section 7)
// Tracks which fields are filled during the adaptive conversation.
// ---------------------------------------------------------------------------

export interface ConversationState {
  age: number | null;
  investmentAmount: number | null;
  goal: string | null;
  incomeStability: 'stable' | 'unstable' | null;
  horizonYears: number | null;
  riskReaction: string | null;
}

/** Helper to create an empty conversation state */
export function emptyConversationState(): ConversationState {
  return {
    age: null,
    investmentAmount: null,
    goal: null,
    incomeStability: null,
    horizonYears: null,
    riskReaction: null,
  };
}

/** Check if all required fields are filled */
export function isConversationComplete(state: ConversationState): boolean {
  return (
    state.age !== null &&
    state.investmentAmount !== null &&
    state.goal !== null &&
    state.incomeStability !== null &&
    state.horizonYears !== null &&
    state.riskReaction !== null
  );
}

// ---------------------------------------------------------------------------
// User Profile — derived from ConversationState after conversation completes
// ---------------------------------------------------------------------------

export interface UserProfileData {
  sessionId: string;
  age: number | null;
  investmentAmount: number | null;
  horizonYears: number | null;
  riskCapacity: 'low' | 'medium' | 'high' | null;
  goal: string | null;
  incomeStability: 'stable' | 'unstable' | null;
  riskReaction: string | null;
}

// ---------------------------------------------------------------------------
// Fund Metrics — pre-computed by the Analytics Service
// ---------------------------------------------------------------------------

export interface FundMetricsData {
  schemeCode: string;
  schemeName: string;
  category: string;
  fundHouse?: string;
  cagr: number;
  volatility: number;
  sharpeRatio: number;
  maxDrawdown: number;
  expenseRatio: number;
  lastUpdated?: string;
}

// ---------------------------------------------------------------------------
// Report — generated by the Report Composer
// ---------------------------------------------------------------------------

export interface ReportData {
  sessionId: string;
  recommendedCategory: string;
  narrativeText: string;
  metricsUsed: FundMetricsData[];
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// Chat Message — a single message in a conversation (replaces Answer)
// ---------------------------------------------------------------------------

export interface ChatMessageData {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  toolCalls?: Array<{
    name: string;
    args: Record<string, any>;
    result?: any;
  }>;
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// Chat Stream Events — SSE event types
// ---------------------------------------------------------------------------

export interface ChatStreamTokenEvent {
  type: 'token';
  content: string;
}

export interface ChatStreamSessionEvent {
  type: 'session';
  sessionId: string;
}

export interface ChatStreamToolCallEvent {
  type: 'tool_call';
  toolCall: {
    id: string;
    name: string;
    args: string;
  };
  toolResult?: any;
}

export interface ChatStreamDoneEvent {
  type: 'done';
  content?: string;
  finishReason?: string;
}

export interface ChatStreamErrorEvent {
  type: 'error';
  content: string;
}

export type ChatStreamEvent =
  | ChatStreamTokenEvent
  | ChatStreamSessionEvent
  | ChatStreamToolCallEvent
  | ChatStreamDoneEvent
  | ChatStreamErrorEvent;

// ---------------------------------------------------------------------------
// Answer — legacy type (kept for backward compat)
// ---------------------------------------------------------------------------

export interface AnswerData {
  sessionId: string;
  question: string;
  answerText: string;
  fieldTargeted: string;
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// API response types
// ---------------------------------------------------------------------------

export interface NextQuestionResponse {
  nextQuestion: string;
  fieldTargeted: string;
  isComplete: boolean;
  conversationState?: ConversationState;
}

export interface StartConversationResponse {
  sessionId: string;
  firstQuestion: string;
  fieldTargeted: string;
}

// ---------------------------------------------------------------------------
// Fund Recommendation and Report Types (Vite Frontend & Node/Express Backend)
// ---------------------------------------------------------------------------

export interface FundRecommendation {
  category: string;
  categoryName: string;
  emoji: string;
  description: string;
  color: string;
  riskTag: string;
  representativeMetrics: {
    schemeCode: string;
    schemeName: string;
    category: string;
    cagr1yr: number;
    cagr3yr: number;
    cagr5yr: number;
    cagr10yr: number;
    volatilityAnnualized: number;
    sharpeRatio: number;
    maxDrawdown: number;
    expenseRatio: number;
    aum: number;
    computedAt: string;
  };
  topSchemes: {
    schemeCode: string;
    schemeName: string;
    category: string;
    amcName: string;
  }[];
  aiExplanation: string;
  suitabilityScore: number;
}

export interface Report {
  sessionId: string;
  profileSummary: {
    riskLevel: string;
    horizon: string;
    goal: string;
    headline: string;
    description: string;
    emoji: string;
  };
  recommendedFunds: FundRecommendation[];
  generatedAt: string;
  disclaimer: string;
}

