/**
 * chat.service.ts — Centralized AI Chat Service
 *
 * ALL assistant responses are generated by the Ollama LLM (qwen3:4b).
 * The backend NEVER generates conversational text — only manages state,
 * executes tools, and streams LLM responses.
 *
 * Flow:
 *  1. Load conversation history from MongoDB
 *  2. Load current user profile state
 *  3. Build system prompt with persona + context + tool definitions
 *  4. Stream the LLM response back (SSE)
 *  5. Handle any tool calls (updateProfile, getProfile, etc.)
 *  6. Save messages to history
 */

import { ChatMessage } from '../db/models/ChatMessage.model';
import { UserProfile } from '../db/models/UserProfile.model';
import { ConversationSession } from '../db/models/ConversationSession.model';
import {
  chatMessagesStream,
  chatMessagesCompletion,
  StreamChunk,
} from './ollama.service';
import type { ChatCompletionMessageParam, ChatCompletionTool } from './ollama.service';
import {
  updateUserProfile,
  getProfileState,
  classifyRisk,
  recommendCategory,
  profileToState,
  getMissingFields,
} from './profile.service';
import mongoose from 'mongoose';

// ---------------------------------------------------------------------------
// System Prompt — persona + context (NO hardcoded conversational text)
// ---------------------------------------------------------------------------

function buildSystemPrompt(profileContext: string): string {
  return `You are a friendly, knowledgeable, and empathetic financial advisor named "Advisor" who specializes in Indian mutual funds. You help first-time investors understand investing concepts.

PERSONALITY:
- Warm, encouraging, and patient
- You explain complex financial concepts in simple language
- You use relatable Indian examples (₹ rupees, Indian mutual fund categories, Indian market context)
- You keep responses concise (2-4 sentences for conversational exchanges)
- You are a voice conversation assistant, so be natural and conversational

CAPABILITIES:
- You can discuss any topic related to mutual funds, investing, personal finance
- You can explain concepts like SIP, CAGR, NAV, expense ratio, risk, diversification
- You can help users understand their risk profile
- You are NOT limited to collecting data — you can answer questions, give explanations, and have natural conversations

PROFILE COLLECTION:
- During conversation, naturally gather the user's information when they share it
- The fields you need are: age, investmentAmount (in ₹), goal (retirement/wedding/house/education/emergency/wealth/other), incomeStability (stable/unstable), horizonYears, riskReaction (how they'd react to a 15% drop)
- Use the updateUserProfile tool when you've extracted information from the user's messages
- Do NOT ask all questions at once — gather information naturally through conversation
- Acknowledge what the user says before asking follow-up questions

CURRENT USER PROFILE:
${profileContext}

RULES:
1. NEVER say "I'm just an AI" or "I can't give financial advice" — you ARE a financial advisor (educational)
2. Use "historically" framing when discussing fund performance — never say "you should buy"
3. Always include the disclaimer that past performance doesn't guarantee future returns when discussing specific funds
4. Be proactive — if the user seems confused, offer to explain
5. Keep responses SHORT for voice conversation — no long paragraphs
6. When all profile fields are gathered, let the user know you can generate their personalized report
7. Respond in the same language the user uses (English or Hinglish)
8. Do NOT use markdown formatting — speak naturally as this is a voice/chat conversation`;
}

// ---------------------------------------------------------------------------
// Tool Definitions — exposed to the LLM for function calling
// ---------------------------------------------------------------------------

const TOOLS: ChatCompletionTool[] = [
  {
    type: 'function',
    function: {
      name: 'updateUserProfile',
      description: 'Save or update user profile information that was shared during the conversation. Call this when the user mentions their age, investment amount, goal, income type, investment horizon, or risk tolerance. You can update one or more fields at a time.',
      parameters: {
        type: 'object',
        properties: {
          age: {
            type: 'number',
            description: 'User\'s age in years',
          },
          investmentAmount: {
            type: 'number',
            description: 'Amount user wants to invest in rupees. Convert shorthand: "50k" = 50000, "2 lakh" = 200000, "5L" = 500000',
          },
          goal: {
            type: 'string',
            enum: ['retirement', 'wedding', 'house', 'education', 'emergency', 'wealth', 'other'],
            description: 'User\'s primary investment goal',
          },
          incomeStability: {
            type: 'string',
            enum: ['stable', 'unstable'],
            description: '"stable" for salaried/government/regular income, "unstable" for freelance/business/variable income',
          },
          horizonYears: {
            type: 'number',
            description: 'Number of years the user plans to stay invested. "long term" = 10, "short term" = 2, "medium term" = 5',
          },
          riskReaction: {
            type: 'string',
            description: 'How the user would react if their investment dropped 15% — their emotional response as free text',
          },
        },
        required: [],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'getUserProfile',
      description: 'Get the current state of the user\'s profile to check what information has been collected and what is still missing.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
    },
  },
];

// ---------------------------------------------------------------------------
// Tool Handlers — execute backend business logic
// ---------------------------------------------------------------------------

async function handleToolCall(
  sessionId: string,
  toolName: string,
  toolArgs: Record<string, any>
): Promise<any> {
  switch (toolName) {
    case 'updateUserProfile': {
      const result = await updateUserProfile(sessionId, toolArgs);
      return {
        success: true,
        ...result,
        message: result.isComplete
          ? 'Profile is now complete! Risk has been classified. You can offer to generate their personalized report.'
          : `Updated profile. Still missing: ${result.missingFields.join(', ')}`,
      };
    }
    case 'getUserProfile': {
      const result = await getProfileState(sessionId);
      return result;
    }
    default:
      return { error: `Unknown tool: ${toolName}` };
  }
}

// ---------------------------------------------------------------------------
// Build profile context string for system prompt
// ---------------------------------------------------------------------------

async function buildProfileContext(sessionId: string): Promise<string> {
  try {
    const profile = await UserProfile.findOne({
      sessionId: new mongoose.Types.ObjectId(sessionId),
    });
    if (!profile) return 'No profile data collected yet. Start by getting to know the user.';

    const state = profileToState(profile);
    const missing = getMissingFields(state);

    const lines: string[] = [];
    if (state.age !== null) lines.push(`- Age: ${state.age}`);
    if (state.investmentAmount !== null) lines.push(`- Investment Amount: ₹${state.investmentAmount.toLocaleString('en-IN')}`);
    if (state.goal !== null) lines.push(`- Goal: ${state.goal}`);
    if (state.incomeStability !== null) lines.push(`- Income: ${state.incomeStability}`);
    if (state.horizonYears !== null) lines.push(`- Horizon: ${state.horizonYears} years`);
    if (state.riskReaction !== null) lines.push(`- Risk Reaction: provided`);

    if (lines.length === 0) {
      return 'No profile data collected yet. Start by getting to know the user.';
    }

    let ctx = `Collected so far:\n${lines.join('\n')}`;
    if (missing.length > 0) {
      ctx += `\n\nStill need: ${missing.join(', ')}`;
    } else {
      ctx += '\n\n✅ All fields collected! Profile is complete. Offer to generate their personalized report.';
      if (profile.riskCapacity) {
        ctx += `\nRisk Capacity: ${profile.riskCapacity}`;
        ctx += `\nRecommended Category: ${recommendCategory(profile.riskCapacity, profile.horizonYears)}`;
      }
    }

    return ctx;
  } catch {
    return 'No profile data collected yet. Start by getting to know the user.';
  }
}

// ---------------------------------------------------------------------------
// Load conversation history from MongoDB → OpenAI message format
// ---------------------------------------------------------------------------

async function loadHistory(sessionId: string): Promise<ChatCompletionMessageParam[]> {
  const messages = await ChatMessage.find({
    sessionId: new mongoose.Types.ObjectId(sessionId),
  }).sort({ createdAt: 1 });

  return messages.map((m) => ({
    role: m.role as 'user' | 'assistant' | 'system',
    content: m.content,
  }));
}

// ---------------------------------------------------------------------------
// Save a message to MongoDB
// ---------------------------------------------------------------------------

async function saveMessage(
  sessionId: string,
  role: 'user' | 'assistant' | 'system',
  content: string,
  toolCalls?: Array<{ name: string; args: any; result?: any }>
): Promise<void> {
  await new ChatMessage({
    sessionId: new mongoose.Types.ObjectId(sessionId),
    role,
    content,
    toolCalls: toolCalls && toolCalls.length > 0 ? toolCalls : undefined,
  }).save();
}

// ---------------------------------------------------------------------------
// Clean LLM response — remove thinking tags from qwen3
// ---------------------------------------------------------------------------

function cleanResponse(text: string): string {
  return text
    .replace(/<think>[\s\S]*?<\/think>/g, '')
    .trim();
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Start a new chat session. Creates the session, profile, and generates
 * the AI's greeting message via the LLM (NOT hardcoded).
 * Returns sessionId and an async generator for streaming the greeting.
 */
export async function startChat(): Promise<{
  sessionId: string;
  stream: AsyncGenerator<StreamChunk, void, unknown>;
}> {
  // Create session
  const session = new ConversationSession();
  await session.save();
  const sessionId = session._id.toString();

  // Create empty profile
  const profile = new UserProfile({
    sessionId: new mongoose.Types.ObjectId(sessionId),
  });
  await profile.save();

  // Build system prompt
  const profileCtx = await buildProfileContext(sessionId);
  const systemPrompt = buildSystemPrompt(profileCtx);

  // Generate greeting via LLM
  const messages: ChatCompletionMessageParam[] = [
    { role: 'system', content: systemPrompt },
    {
      role: 'user',
      content: '[SYSTEM: The user just opened the chat. Generate a warm, friendly greeting and introduce yourself. Ask them a natural opening question to get the conversation started. Keep it SHORT — 2-3 sentences max.]',
    },
  ];

  // Create a generator that streams the greeting from Ollama
  async function* greetingStream(): AsyncGenerator<StreamChunk, void, unknown> {
    let fullResponse = '';

    try {
      for await (const chunk of chatMessagesStream(messages, { temperature: 0.8, num_predict: 1024 })) {
        if (chunk.type === 'token') {
          const cleaned = chunk.content?.replace(/<\/?think>/g, '') || '';
          if (cleaned) {
            fullResponse += cleaned;
            yield { type: 'token', content: cleaned };
          }
        } else if (chunk.type === 'done') {
          fullResponse = cleanResponse(fullResponse);
          if (!fullResponse) {
            throw new Error("Model generated empty response");
          }
          yield { type: 'done', content: fullResponse, finishReason: chunk.finishReason };
        }
      }
    } catch (err: any) {
      if (!fullResponse) {
        throw err;
      } else {
        throw err;
      }
    }

    // Save the greeting to history
    await saveMessage(sessionId, 'assistant', fullResponse);
  }

  return { sessionId, stream: greetingStream() };
}

/**
 * Process a user message — stream the AI's response.
 * Handles tool calls automatically and continues generation.
 *
 * @param sessionId - The conversation session ID
 * @param userMessage - The user's message text
 * @returns An async generator yielding stream chunks (tokens, tool calls, done)
 */
export async function* streamChatResponse(
  sessionId: string,
  userMessage: string
): AsyncGenerator<StreamChunk & { toolResult?: any }, void, unknown> {
  // 1. Save user message
  await saveMessage(sessionId, 'user', userMessage);

  // 2. Load conversation history
  const history = await loadHistory(sessionId);

  // 3. Build system prompt with current profile state
  const profileCtx = await buildProfileContext(sessionId);
  const systemPrompt = buildSystemPrompt(profileCtx);

  // 4. Construct messages array
  const messages: ChatCompletionMessageParam[] = [
    { role: 'system', content: systemPrompt },
    ...history,
  ];

  // 5. Stream from LLM with tools
  let fullResponse = '';
  let toolCallsExecuted: Array<{ name: string; args: any; result: any }> = [];
  let hasToolCalls = false;
  let pendingToolCalls: Array<{ id: string; name: string; args: string }> = [];
  let isProfileComplete = false;

  // First pass — stream and collect
  for await (const chunk of chatMessagesStream(messages, { temperature: 0.7, num_predict: 2048 }, TOOLS)) {
    if (chunk.type === 'token') {
      // Clean thinking tags in real-time
      const cleaned = chunk.content?.replace(/<\/?think>/g, '') || '';
      if (cleaned) {
        fullResponse += cleaned;
        yield { type: 'token', content: cleaned };
      }
    } else if (chunk.type === 'tool_call' && chunk.toolCall) {
      hasToolCalls = true;
      pendingToolCalls.push(chunk.toolCall);
    } else if (chunk.type === 'done') {
      // If there are tool calls, handle them before marking done
      if (!hasToolCalls) {
        // Clean the full response
        fullResponse = cleanResponse(fullResponse);
        yield { type: 'done', content: fullResponse, finishReason: chunk.finishReason, profileComplete: isProfileComplete };
      }
    }
  }

  // 6. Handle tool calls if any
  if (hasToolCalls && pendingToolCalls.length > 0) {
    for (const tc of pendingToolCalls) {
      let args: Record<string, any> = {};
      try {
        args = JSON.parse(tc.args || '{}');
      } catch {
        args = {};
      }

      // Execute the tool
      const toolResult = await handleToolCall(sessionId, tc.name, args);
      toolCallsExecuted.push({ name: tc.name, args, result: toolResult });

      if (toolResult?.isComplete) {
        isProfileComplete = true;
      }

      // Yield tool call info to the frontend
      yield {
        type: 'tool_call',
        toolCall: tc,
        toolResult,
      };
    }

    // 7. Continue generation with tool results
    // Build updated messages with tool call + results for the LLM to continue
    const updatedProfileCtx = await buildProfileContext(sessionId);
    const updatedSystemPrompt = buildSystemPrompt(updatedProfileCtx);

    const continuationMessages: ChatCompletionMessageParam[] = [
      { role: 'system', content: updatedSystemPrompt },
      ...history,
      // Add tool result context as assistant message
      {
        role: 'assistant',
        content: `[Tool calls executed: ${toolCallsExecuted.map(t =>
          `${t.name}(${JSON.stringify(t.args)}) → ${JSON.stringify(t.result)}`
        ).join('; ')}]\n\nNow respond naturally to the user based on the tool results. Do NOT mention tool calls or technical details. Just acknowledge what was saved and continue the conversation.`,
      },
      {
        role: 'user',
        content: userMessage,
      },
    ];

    // Stream the continuation
    let continuationResponse = '';
    for await (const chunk of chatMessagesStream(continuationMessages, { temperature: 0.7, num_predict: 1024 })) {
      if (chunk.type === 'token') {
        const cleaned = chunk.content?.replace(/<\/?think>/g, '') || '';
        if (cleaned) {
          continuationResponse += cleaned;
          yield { type: 'token', content: cleaned };
        }
      } else if (chunk.type === 'done') {
        continuationResponse = cleanResponse(continuationResponse);
        fullResponse = continuationResponse;
        yield { type: 'done', content: continuationResponse, finishReason: chunk.finishReason, profileComplete: isProfileComplete };
      }
    }
  }

  // 8. Save assistant response to history
  if (fullResponse) {
    await saveMessage(sessionId, 'assistant', fullResponse, toolCallsExecuted.length > 0 ? toolCallsExecuted : undefined);
  }
}

/**
 * Get all messages for a session.
 */
export async function getMessages(sessionId: string) {
  const messages = await ChatMessage.find({
    sessionId: new mongoose.Types.ObjectId(sessionId),
  }).sort({ createdAt: 1 });

  return messages.map((m) => ({
    id: m._id.toString(),
    role: m.role,
    content: m.content,
    toolCalls: m.toolCalls,
    createdAt: m.createdAt,
  }));
}
