/**
 * chat.service.ts — Centralized AI Chat Service
 *
 * ALL assistant responses are generated by the Ollama LLM (qwen3:4b).
 * The backend NEVER generates conversational text — only manages state,
 * executes tools, and streams LLM responses.
 *
 * Flow:
 *  1. Load conversation history from MongoDB
 *  2. Load current user profile state
 *  3. Build system prompt with persona + context + tool definitions
 *  4. Stream the LLM response back (SSE)
 *  5. Handle any tool calls (updateProfile, getProfile, etc.)
 *  6. Save messages to history
 */

import { ChatMessage } from '../db/models/ChatMessage.model';
import { FinancialProfile } from '../db/models/FinancialProfile';
import { User } from '../db/models/User';
import { ConversationSession } from '../db/models/ConversationSession.model';
import {
  chatMessagesStream,
  chatMessagesCompletion,
  StreamChunk,
} from './ollama.service';
import type { ChatCompletionMessageParam, ChatCompletionTool } from './ollama.service';
import {
  updateUserProfile,
  getProfileState,
  classifyRisk,
  recommendCategory,
  profileToState,
  getMissingFields,
} from './profile.service';
import mongoose from 'mongoose';

// ---------------------------------------------------------------------------
// System Prompt — persona + context (NO hardcoded conversational text)
// ---------------------------------------------------------------------------

function buildSystemPrompt(profileContext: string, userName: string): string {
  return `You are a friendly, knowledgeable, and empathetic financial advisor named "Advisor" who specializes in Indian mutual funds. You help first-time investors understand investing concepts.
You are talking to ${userName}. Address them naturally by their name occasionally.

PERSONALITY:
- Warm, encouraging, and patient
- You explain complex financial concepts in simple language
- You use relatable Indian examples (₹ rupees, Indian mutual fund categories, Indian market context)
- You keep responses concise (1-2 sentences for conversational exchanges)
- You are a voice conversation assistant, so be natural and conversational

CAPABILITIES:
- You can discuss any topic related to mutual funds, investing, personal finance
- You can explain concepts like SIP, CAGR, NAV, expense ratio, risk, diversification
- You can help users understand their risk profile
- You are NOT limited to collecting data — you can answer questions, give explanations, and have natural conversations

PROFILE COLLECTION:
- During conversation, naturally gather the user's information when they share it
- The fields you need are: age, investmentAmount (in ₹), goal, horizonYears, riskReaction
- Use the updateUserProfile tool immediately when you extract any of these from the user's messages
- Acknowledge what the user says naturally.

CURRENT USER PROFILE:
${profileContext}

RULES:
1. NEVER say "I'm just an AI" or "I can't give financial advice" — you ARE a financial advisor (educational).
2. ALWAYS ask exactly ONE question at a time. Never list multiple questions.
3. Be conversational and varied. DO NOT repeat the exact same phrasing.
4. Keep responses SHORT for voice conversation — 1 or 2 sentences maximum.
5. If the user gives a nonsense answer (like "Hi"), politely steer them back to the topic.
6. When all profile fields are gathered, let the user know you are ready to generate their personalized report.
7. Respond in the same language the user uses (English or Hinglish).
8. Do NOT use markdown formatting — speak naturally as this is a voice/chat conversation.
9. NEVER guess or hallucinate profile fields. If the user only provides one field (e.g. amount), DO NOT assume their goal or horizon.`;
}

// ---------------------------------------------------------------------------
// Tool Definitions — exposed to the LLM for function calling
// ---------------------------------------------------------------------------

const TOOLS: ChatCompletionTool[] = [
  {
    type: 'function',
    function: {
      name: 'updateUserProfile',
      description: 'Save or update user profile information that was shared during the conversation. Call this when the user mentions their age, investment amount, goal, investment horizon, or risk tolerance. You can update one or more fields at a time.',
      parameters: {
        type: 'object',
        properties: {
          age: {
            type: 'number',
            description: 'User\'s age in years',
          },
          investmentAmount: {
            type: 'number',
            description: 'Amount user wants to invest in rupees. Convert shorthand: "50k" = 50000, "2 lakh" = 200000, "5L" = 500000',
          },
          goal: {
            type: 'string',
            enum: ['retirement', 'wedding', 'house', 'education', 'emergency', 'wealth', 'other'],
            description: 'User\'s primary investment goal',
          },
          horizonYears: {
            type: 'number',
            description: 'Number of years the user plans to stay invested',
          },
          riskReaction: {
            type: 'string',
            description: 'How the user would react if their investment dropped by 15% (e.g., "sell", "hold", "buy more")',
          },
        },
        required: [],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'getUserProfile',
      description: 'Get the current state of the user\'s profile to check what information has been collected and what is still missing.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
    },
  },
];

// ---------------------------------------------------------------------------
// Tool Handlers — execute backend business logic
// ---------------------------------------------------------------------------

async function handleToolCall(
  userId: string,
  toolName: string,
  toolArgs: Record<string, any>
): Promise<any> {
  switch (toolName) {
    case 'updateUserProfile': {
      const result = await updateUserProfile(userId, toolArgs);
      return {
        success: true,
        ...result,
        message: result.isComplete
          ? 'Profile is now complete! Risk has been classified. You can offer to generate their personalized report.'
          : `Updated profile. Still missing: ${result.missingFields.join(', ')}`,
      };
    }
    case 'getUserProfile': {
      const result = await getProfileState(userId);
      return result;
    }
    default:
      return { error: `Unknown tool: ${toolName}` };
  }
}

// ---------------------------------------------------------------------------
// Build profile context string for system prompt
// ---------------------------------------------------------------------------

async function buildProfileContext(userId: string): Promise<string> {
  try {
    const profile = await FinancialProfile.findOne({
      userId: new mongoose.Types.ObjectId(userId),
    });

    if (!profile) return 'No profile data collected yet. Start by getting to know the user.';

    let ctx = `Age Group: ${profile.ageGroup || 'Unknown'}\n`;
    ctx += `Monthly Investment: ${profile.monthlyInvestment || 'Unknown'}\n`;
    ctx += `Target Goal: ${profile.targetGoal || 'Unknown'}\n`;
    ctx += `Time Horizon: ${profile.timeHorizon || 'Unknown'}\n`;
    ctx += `Risk Tolerance: ${profile.riskTolerance || 'Unknown'}\n`;

    return ctx;
  } catch {
    return 'No profile data collected yet. Start by getting to know the user.';
  }
}

// ---------------------------------------------------------------------------
// Load conversation history from MongoDB → OpenAI message format
// ---------------------------------------------------------------------------

async function loadHistory(sessionId: string): Promise<ChatCompletionMessageParam[]> {
  const messages = await ChatMessage.find({
    sessionId: new mongoose.Types.ObjectId(sessionId),
  }).sort({ createdAt: 1 });

  return messages.map((m) => ({
    role: m.role as 'user' | 'assistant' | 'system',
    content: m.content,
  }));
}

// ---------------------------------------------------------------------------
// Save a message to MongoDB
// ---------------------------------------------------------------------------

async function saveMessage(
  sessionId: string,
  role: 'user' | 'assistant' | 'system',
  content: string,
  toolCalls?: Array<{ name: string; args: any; result?: any }>
): Promise<void> {
  await new ChatMessage({
    sessionId: new mongoose.Types.ObjectId(sessionId),
    role,
    content,
    toolCalls: toolCalls && toolCalls.length > 0 ? toolCalls : undefined,
  }).save();
}

// ---------------------------------------------------------------------------
// Clean LLM response — remove thinking tags from qwen3
// ---------------------------------------------------------------------------

function cleanResponse(text: string): string {
  return text
    .replace(/<think>[\s\S]*?<\/think>/g, '')
    .trim();
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Start a new chat session. Creates the session, profile, and generates
 * the AI's greeting message via the LLM (NOT hardcoded).
 * Returns sessionId and an async generator for streaming the greeting.
 */
export async function startChat(userId: string): Promise<{
  sessionId: string;
  stream: AsyncGenerator<StreamChunk, void, unknown>;
}> {
  // Create session
  const session = new ConversationSession();
  await session.save();
  const sessionId = session._id.toString();
  
  const user = await User.findById(userId);
  const userName = user?.name || 'Friend';

  // Ensure FinancialProfile exists
  let profile = await FinancialProfile.findOne({ userId });
  if (!profile) {
    await FinancialProfile.create({ userId });
  }

  // Build system prompt
  const profileCtx = await buildProfileContext(userId);
  const systemPrompt = buildSystemPrompt(profileCtx, userName);

  // Generate greeting via LLM
  const messages: ChatCompletionMessageParam[] = [
    { role: 'system', content: systemPrompt },
    {
      role: 'user',
      content: `[SYSTEM: The user just opened the chat. Generate a warm, friendly greeting and address them as ${userName}. Ask them a natural opening question to get the conversation started. Keep it SHORT — 2-3 sentences max.]`,
    },
  ];

  // Create a generator that streams the greeting from Ollama
  async function* greetingStream(): AsyncGenerator<StreamChunk, void, unknown> {
    let fullResponse = '';
    let insideThink = false;  // Track whether we're inside <think>...</think>

    try {
      for await (const chunk of chatMessagesStream(messages, { temperature: 0.8, num_predict: 1024, num_ctx: 8192 })) {
        if (chunk.type === 'token') {
          if (chunk.content) {
            fullResponse += chunk.content;
            yield { type: 'token', content: chunk.content };
          }
        } else if (chunk.type === 'done') {
          // Final cleanup — remove any remaining thinking tags that may have been partial
          fullResponse = cleanResponse(fullResponse);

          if (!fullResponse) {
            console.warn('[chat.service] Greeting stream produced empty response — using fallback');
            fullResponse = `Hi ${userName}! I'm your MF Advisor. I'd love to help you with your investment planning. To get started, could you tell me your age?`;
            yield { type: 'token', content: fullResponse };
          }

          console.log('[chat.service] Greeting generated:', fullResponse.slice(0, 100));
          yield { type: 'done', content: fullResponse, finishReason: chunk.finishReason };
        }
      }
    } catch (err: any) {
      console.error('[chat.service] Greeting stream error:', err?.message || err);
      // If we got nothing, provide a fallback so the user isn't stuck
      if (!fullResponse) {
        fullResponse = `Hi ${userName}! Welcome! I'm your MF Advisor. To help you find the right mutual funds, could you start by telling me your age?`;
        yield { type: 'token', content: fullResponse };
        yield { type: 'done', content: fullResponse, finishReason: 'error_fallback' };
      }
      // Don't re-throw if we have a fallback — let the conversation continue
    }

    // Save the greeting to history
    if (fullResponse) {
      await saveMessage(sessionId, 'assistant', fullResponse);
    }
  }

  return { sessionId, stream: greetingStream() };
}

/**
 * Process a user message — stream the AI's response.
 * Handles tool calls automatically and continues generation.
 *
 * @param sessionId - The conversation session ID
 * @param userMessage - The user's message text
 * @returns An async generator yielding stream chunks (tokens, tool calls, done)
 */
export async function* streamChatResponse(
  sessionId: string,
  userMessage: string,
  userId: string
): AsyncGenerator<StreamChunk & { toolResult?: any }, void, unknown> {
  // 1. Save user message
  await saveMessage(sessionId, 'user', userMessage);

  // 2. Load conversation history
  const history = await loadHistory(sessionId);
  
  const user = await User.findById(userId);
  const userName = user?.name || 'Friend';

  // 3. Build system prompt with current profile state
  const profileCtx = await buildProfileContext(userId);
  const systemPrompt = buildSystemPrompt(profileCtx, userName);

  // 4. Construct messages array. To prevent context window explosion, keep the last 20 messages.
  const MAX_HISTORY = 20;
  const messages: ChatCompletionMessageParam[] = [
    { role: 'system', content: systemPrompt },
    ...history.slice(-MAX_HISTORY),
  ];

  // 5. Stream from LLM with tools
  let fullResponse = '';
  let toolCallsExecuted: Array<{ name: string; args: any; result: any }> = [];
  let hasToolCalls = false;
  let pendingToolCalls: Array<{ id: string; name: string; args: string }> = [];
  let isProfileComplete = false;
  let insideThink = false;  // Track thinking tags

  console.log('[chat.service] Streaming response for session:', sessionId, 'message:', userMessage.slice(0, 50));

  // First pass — stream and collect
  for await (const chunk of chatMessagesStream(messages, { temperature: 0.7, num_predict: 2048, num_ctx: 8192 }, TOOLS)) {
    if (chunk.type === 'token') {
      if (chunk.content) {
        fullResponse += chunk.content;
        yield { type: 'token', content: chunk.content };
      }
    } else if (chunk.type === 'tool_call' && chunk.toolCall) {
      hasToolCalls = true;
      pendingToolCalls.push(chunk.toolCall);
    } else if (chunk.type === 'done') {
      // If there are tool calls, handle them before marking done
      if (!hasToolCalls) {
        // Clean the full response
        fullResponse = cleanResponse(fullResponse);
        yield { type: 'done', content: fullResponse, finishReason: chunk.finishReason, profileComplete: isProfileComplete };
      }
    }
  }

  // 6. Handle tool calls if any
  if (hasToolCalls && pendingToolCalls.length > 0) {
    for (const tc of pendingToolCalls) {
      let args: Record<string, any> = {};
      try {
        args = JSON.parse(tc.args || '{}');
      } catch {
        args = {};
      }

      // Execute the tool
      const toolResult = await handleToolCall(userId, tc.name, args);
      toolCallsExecuted.push({ name: tc.name, args, result: toolResult });

      if (toolResult?.isComplete) {
        isProfileComplete = true;
      }

      // Yield tool call info to the frontend
      yield {
        type: 'tool_call',
        toolCall: tc,
        toolResult,
      };
    }

    // 7. Continue generation with tool results
    // Build updated messages with tool call + results for the LLM to continue
    const updatedProfileCtx = await buildProfileContext(userId);
    const updatedSystemPrompt = buildSystemPrompt(updatedProfileCtx, userName);

    const continuationMessages: ChatCompletionMessageParam[] = [
      { role: 'system', content: updatedSystemPrompt },
      ...history.slice(-MAX_HISTORY).slice(0, -1),
      {
        role: 'user',
        content: `${userMessage}\n\n[SYSTEM NOTIFICATION: Tool calls were just executed successfully based on your input. Results: ${toolCallsExecuted.map(t =>
          `${t.name}(${JSON.stringify(t.args)}) → ${JSON.stringify(t.result)}`
        ).join('; ')}]\nNow respond naturally to the user. Do NOT mention tool calls or technical details. Just acknowledge what was saved and continue the conversation.`,
      }
    ];

    // Stream the continuation
    let continuationResponse = '';
    let insideThinkCont = false;
    for await (const chunk of chatMessagesStream(continuationMessages, { temperature: 0.7, num_predict: 1024, num_ctx: 8192 })) {
      if (chunk.type === 'token') {
        if (chunk.content) {
          continuationResponse += chunk.content;
          yield { type: 'token', content: chunk.content };
        }
      } else if (chunk.type === 'done') {
        continuationResponse = cleanResponse(continuationResponse);
        fullResponse = continuationResponse;
        yield { type: 'done', content: continuationResponse, finishReason: chunk.finishReason, profileComplete: isProfileComplete };
      }
    }
  }

  // 8. Save assistant response to history
  if (fullResponse) {
    await saveMessage(sessionId, 'assistant', fullResponse, toolCallsExecuted.length > 0 ? toolCallsExecuted : undefined);
  }
}

/**
 * Get all messages for a session.
 */
export async function getMessages(sessionId: string) {
  const messages = await ChatMessage.find({
    sessionId: new mongoose.Types.ObjectId(sessionId),
  }).sort({ createdAt: 1 });

  return messages.map((m) => ({
    id: m._id.toString(),
    role: m.role,
    content: m.content,
    toolCalls: m.toolCalls,
    createdAt: m.createdAt,
  }));
}
